services:
  bot-telegram-service:
    build:
      context: ..
      dockerfile: docker/dockerfile
    env_file:
      - ./conf/.env
    command: ["npm", "start"]
    environment:
      - llm_model_name=${llm_model_name}
      - api_server=${api_server}
      - api_server_port=${api_server_port}
      - ollama_api_server_ipaddress=${ollama_api_server_ipaddress}
      - ollama_api_server_port=${ollama_api_server_port}
      - mongo_host=${MONGO_SERVER_IPADDRESS}
      - mongo_port=${MONGODB_PORT}
    ports:
      - "${api_server_port}:4000"
    cpus: 4
    restart: always
    depends_on:
      - mongo-db-to-auth-telegram-service
    network_mode: "host"
    #networks:
#      - bot-telegram-chatbot

  mongo-db-to-auth-telegram-service:
    container_name: mongo-db-to-auth-telegram-container
    image: mongo:5
    user: root
    restart: always
    tty: true
    stdin_open: true
    env_file:
      - ./conf/.env
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_SERVER_IPADDRESS=${MONGO_SERVER_IPADDRESS}
      - MONGODB_PORT=${MONGODB_PORT}
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
    command: mongod --replSet myReplicaSet --bind_ip_all
    volumes:
      - ../src/database/data:/data/db
      - ../src/database/scripts/replicaset.sh:/docker-entrypoint-initdb.d/replicaset.sh
    ports:
      - ${MONGODB_PORT}:27017
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2g
    network_mode: "host"
    #networks:
    # - bot-telegram-chatbot

  api-mongo-db-communication-service:
    container_name: api-mongo-db-communication-container
    build:
      context: ..
      dockerfile: src/api/docker/dockerfile
    env_file:
      - ./conf/.env
    environment:
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      # use the internal Docker DNS name for the Mongo service
      - MONGO_SERVER_IPADDRESS=${MONGO_SERVER_IPADDRESS}
      # match what your code reads: process.env.MONGODB_PORT
      - MONGODB_PORT=${MONGODB_PORT}
      - API_BASE_URL=${API_BASE_URL}
      - API_BASE_URL_PORT=${API_BASE_URL_PORT}
    command: bash -c "cd /app/src/api && npm start"
    restart: always
    ports:
      - "${API_BASE_URL_PORT}:3000"
    depends_on:
      - mongo-db-to-auth-telegram-service
      - bot-telegram-service
    network_mode: "host"
    #networks:
#      - bot-telegram-chatbot
  docling-inference:
    image: ghcr.io/aidotse/docling-inference:latest
    environment:
      - NUM_WORKERS_DOCLING=${NUM_WORKERS_DOCLING}
      - API_DOCLING_IPADDRES=${API_DOCLING_IPADDRES}
      - API_DOCLING_PORT=${API_DOCLING_PORT}
    restart: always
    ports:
      - "${API_DOCLING_PORT}:8080"      
    volumes:
      - ../docling/cache/hf_cache:/root/.cache/huggingface:rw
      - ../docling/cache/ocr_cache:/root/.EasyOCR:rw
    # ❌ Remova ou comente a seção abaixo
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]


networks:
  bot-telegram-chatbot:
    driver: bridge
