FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first (for better caching)
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ../ .

# Expose the port your app runs on (if applicable, e.g., 3000)
EXPOSE 4000 
EXPOSE 11434
