# Usar a imagem base do Node.js 18
FROM node:18-buster

# Ajuste do fuso horário
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first (for better caching)
COPY ../package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ../ .

# Expose the port your app runs on (if applicable, e.g., 3000)
EXPOSE 4000 
EXPOSE 11434
