# Usar a imagem base do Node.js 18
FROM node:18-buster

# Ajuste do fuso horário
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos necessários para instalar as dependências
COPY ../../package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código da aplicação
COPY ../../ .

# Expõe a porta usada pela API
EXPOSE 3000

# Comando para iniciar a API
CMD ["npm", "start"]